config/routes.rb
Rails.application.routes.draw do

  root :to => 'categories#index'

  get 'categories/:id/posts' => 'posts#index', :as => "posts"
  get 'categories/:id/posts/new' => "posts#new", :as => "new_post"

  resources :posts, except: [:index, :new]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :posts

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  	@categories = Category.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
		@category = Category.find(params[:id])
		@posts = Post.where(category: @category)		
	end

	def show
		@post = Post.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
<%= link_to category.name, posts_path(category.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= link_to post.title, post_path(post.id) %>
<% end %>

app/views/posts/show.html.erb
<p><%= @post.title %></p>
<p><%= @post.description %></p>